apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - con.yaml
  - deploy.yaml
  - serve.yaml
  - name.yaml

patches:
  - target: {} # apply patch to all resources
    patch: |- # you can add nested value and with any naming, even if kubectl doesn't support it
      - op: add
        path: /metadata/shit
        value:
          poo:
            mocha: my-namespace
  - target:
      labelSelector: "purpose=test" # add common lables to all your resources
    patch: |- # it will override all previous patch for this resource on that field
      - op: add
        path: /metadata/shit
        value: my-namespace
  - target:
      kind: Deployment
      name: nginx-deployment
      namespace: default
      group: apps
      version: v1
    patch: |-
      - op: add
        path: /metadata/namespace
        value: my-namespace
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: nginx:latest
    options:
      allowNameChange: false
      allowKindChange: false
  - target:
      namespace: default
      group: ""
      version: v1
      kind: Service
      name: my-service
    patch: |-
      - op: add
        path: /metadata/namespace
        value: my-namespace
    options:
      allowNameChange: false
      allowKindChange: false
  - target:
      namespace: my-namespace
      group: ""
      version: v1
      kind: Service
      name: my-service
    patch: |-
      - op: remove
        path: /metadata/shit
  - target: {}
    patch: |- # delete field for all resources
      - op: add
        path: /metadata/shit
        value: na
      - op: remove
        path: /metadata/shit
