apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-controller-role
rules:
  - apiGroups: ["init.com"]
    resources: ["nginxes"]      # plural of your CRD
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "deployments"] # if you manage pods/deployments
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-controller-role
subjects:
  - kind: ServiceAccount
    name: nginx-controller-sa
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-controller-startup-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-startup-nginx
  template:
    metadata:
      labels:
        app: controller-startup-nginx
    spec:
      serviceAccountName: nginx-controller-sa
      containers:
      - name: controller-startup-nginx
        image: us-central1-docker.pkg.dev/lrn-crd/crdcontroller/controller-startup-nginx:latest
