apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxes.init.com
spec:
  group: init.com
  names:
    kind: NginxStart
    plural: nginxes
    singular: nginx
    shortNames:
    - ng
  scope: Namespaced
  versions:
  - name: v100
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              externalLBPort:
                type: integer
            required: ["externalLBPort"]
        required: ["spec", "apiVersion", "kind"]
