apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: messages.init.com
spec:
  group: init.com
  names: # watch out to not overide existing ones
    kind: Message
    plural: messages
    singular: message
    shortNames:
    - msg
  scope: Namespaced
  versions:
  - name: v100
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              text:
                type: string
            required: ["text"]
        required: ["spec", "apiVersion", "kind"]
