apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxstarts.init.com
spec:
  group: init.com
  names: # watch out to not overide existing ones
    kind: NginxStart
    plural: nginxstarts
    singular: nginxstart
    shortNames:
    - ngst
  scope: Namespaced
  versions:
  - name: v100
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              nodePort:
                type: integer
            required: ["nodePort"]
        required: ["spec", "apiVersion", "kind"]
